# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Put your favicon.ico into `hexo-site/source/` directory.
favicon: /favicon.ico

# Specify the date when the site was setup
since: 2015

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss: /atom.xml

# -------------------------------------------------------
# ui config
# -------------------------------------------------------
# When running the site in a subdirectory (e.g. domain.tld/blog), remove the leading slash (/archives -> archives)
menu:
  home: /
  archives: /archives
  about: /about
menu_icons:
  enable: true
  home: home
  archives: archive
  about: user


# Sidebar widgets
widgets:
- profile
- toc
- search
- recent_posts
- category
#- tag
- tagcloud
- archive

# profile widget
# Key is the link label showing to end users. Value is the target link 
link:
  github: https://github.com/noob9527
  weibo: http://weibo.com/p/1005052678297054
  
# toc widget
toc: 
  number: false

# max recent posts
recent_posts: 10

# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of the item and value is the name of FontAwsome icon. Key is case-senstive.
#   When an globe mask icon presenting up means that the item has no mapping icon.
link_icons:
  weibo: weibo
  github: github

# -------------------------------------------------------
# Third party service config
# -------------------------------------------------------
# Duoshuo(comments and share)
duoshuo:
  shortname: noob9527
  share: true
  ua_enable: true
  user_id: 6272551112717370000
  admin_nickname: xy
  hotarticle: false

# MathJax Support
mathjax:
  enable: true
  cdn: //cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# analytics
baidu_analytics: 855dd1a156248c0c337788236167c870
google_analytics: UA-76868752-1
tencent_analytics: 55612284

# site verification for commit the sitemap
google_site_verification: 9GCG5tynfuvxF_9_xHvo8tvc7CqHeqKMZQqda25rDPs
baidu_site_verification: YjSOMYjRFK

# baidu seo
baidu_push: true

# -------------------------------------------------------
# backend config
# -------------------------------------------------------
# less
less:
 compress: true
